#spring.application.name=Hotel-Micro-Service
#server.port=8082
#spring.datasource.url=jdbc:mysql://localhost:3306/hoteldb
#spring.datasource.username=root
#spring.datasource.password=Harsh@pass
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.show-sql=true
#
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring:
  application:
    name: Hotel-Micro-Service
  datasource:
    url: jdbc:mysql://localhost:3306/hoteldb
    username: root
    password: Harsh@pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8081/eureka/